project_id = "xfbvkaiyvwgnlbhgjmia"

[functions.ai-storytelling]
verify_jwt = false

[functions.github-sync]
verify_jwt = true

[functions.track-analytics]
verify_jwt = false

[functions.generate-portfolio]
verify_jwt = true